Repository exercism/d, pull requests merged in 2024-03, with the labels that each got.

#226 Update resistor-color-duo tests
  exercises/practice/resistor-color-duo/.meta/tests.toml
  exercises/practice/resistor-color-duo/source/resistor_color_duo.d
Labels: x:action/sync, x:rep/tiny

#225 Sync triangle tests
  exercises/practice/triangle/.meta/tests.toml
  exercises/practice/triangle/example/triangle.d
  exercises/practice/triangle/source/triangle.d
Labels: x:action/sync, x:rep/tiny

#219 Add space-age
  config.json
  exercises/practice/space-age/.docs/instructions.md
  exercises/practice/space-age/.meta/config.json
  exercises/practice/space-age/.meta/tests.toml
  exercises/practice/space-age/dub.sdl
  exercises/practice/space-age/example/space_age.d
  exercises/practice/space-age/source/space_age.d
Labels: x:module/practice-exercise, x:rep/medium

#220 Add eliud's eggs
  config.json
  exercises/practice/eliuds-eggs/.docs/instructions.md
  exercises/practice/eliuds-eggs/.docs/introduction.md
  exercises/practice/eliuds-eggs/.meta/config.json
  exercises/practice/eliuds-eggs/.meta/tests.toml
  exercises/practice/eliuds-eggs/dub.sdl
  exercises/practice/eliuds-eggs/example/eliuds_eggs.d
  exercises/practice/eliuds-eggs/source/eliuds_eggs.d
Labels: x:module/practice-exercise, x:rep/medium

#221 Add allergies
  config.json
  exercises/practice/allergies/.docs/instructions.md
  exercises/practice/allergies/.meta/config.json
  exercises/practice/allergies/.meta/tests.toml
  exercises/practice/allergies/dub.sdl
  exercises/practice/allergies/example/allergies.d
  exercises/practice/allergies/source/allergies.d
Labels: x:module/practice-exercise, x:rep/medium

#231 two-fer: sync
  exercises/practice/two-fer/.docs/instructions.md
  exercises/practice/two-fer/.docs/introduction.md
Labels: x:size/tiny

#230 sieve: sync
  exercises/practice/sieve/.docs/instructions.md
Labels: x:size/tiny
